### ISSUE TITLE
File not found if path contains umlauts

### ISSUE THREAD

**Issue by hampoelz** [rotdrop/nextcloud-app-files-archive#45] opened 2024-05-28 13:32 UTC
After mounting a .zip file, I can open the documents and images contained in it as long as the file name or one of its parent folders does not contain an umlaut. In case of umlauts, the file does not open and the following error is displayed: `NonExistentArchiveFileException File "Path or File with umlaut.pdf" does not exist in archive`.

**Comment by rotdrop** [comment] 2024-05-28 13:36
I think this is a duplicate of (parts of) #42 and fixed with commit 2f0cc75. Can you please check with the latest pre-release or clone one of the release branches stable28 / stable29?

**Comment by rotdrop** [comment] 2024-05-28 15:41
You are right, this archive does not work. It lists correctly, but the files cannot be opened.

Can we please first verify whether you really use  a backend named "Zip" or rather the "SevenZip" Backend? I think so  ...

If I try to use 7z with your archive on the command line, then setting the locale to be UTF-8 aware actually leads to strange handling of the contained multibyte characters in the console, but this might be a console bug. When I paste the output here or into any decent editor, then the 'ö'  (in particular) is correctly rendered.

I have to investigate further where things break.

**Comment by hampoelz** [comment] 2024-05-28 15:56
The Nextcloud detail view explicitly displays "Zip". Also, as far as I know, 7zip should not be installed in my Nextcloud docker container. However, I used the following 7zip command on my local system to create the archive: `7zz a -mx9 -r "Test Archive.zip" "Test Archive"`

**Comment by rotdrop** [comment] 2024-05-28 17:31
> The Nextcloud detail view explicitly displays "Zip" as backend driver. Also, as far as I know, 7zip should not be installed in my Nextcloud docker container. However, I used 7zip to create the archive on my local system: `7zz a -mx9 -r "Test Archive.zip" "Test Archive"`

Thanks, then the bad news is: despite the latest UTF-8 locale wrapper it doesn't work with neither the Zip or the SevenZip backend.

**Comment by rotdrop** [comment] 2024-05-28 23:19
This .DS_Store file in the archive implies that the archive was created on an apple computer? Just asking because apple has some conventions for some UTF-8 multibyte characters than the rest of the world. Nevertheless it should just work, of course.

**Comment by rotdrop** [comment] 2024-05-28 23:56
So yes, one of those things which makes apple _special_. See for example here for an explanation:

https://stackoverflow.com/questions/5581857/git-and-the-umlaut-problem-on-mac-os-x

So what happens: apple has this other convention of storing "special" characters. I suppose that at some point Nextcloud does some normalization of the filename -- or maybe even PHP somehow changes things. Now Nextcloud tries to open a file and requests to fetch an archive member with the NC convention of storing "Umlaute" (and other "complicated" UTF-8 characters). Your on-the-apple created archive however uses the other convention. Hence the two names do not really match.

I am actually quite fed up with apple always doing things in a way that hinders using apple things together with the rest of the world. Anyhow, one solution would be to try to detect which convention of representing file names is used inside the archive file and if necessary translate  the Nextcloud filename first to the apple convention. This would solve the problem.

**Comment by rotdrop** [comment] 2024-05-29 00:36
Here ist the piece of code in Nextcloud which does the path normalization

https://github.com/nextcloud/server/blob/ddb840c36babd02abedce7da41b0c04849009edb/lib/private/Files/Filesystem.php#L619

which finally uses the PHP class [Normalizer](https://www.php.net/manual/de/class.normalizer.php) which can translate between NFC (PHP and probably most non-apple stuff) and NFD (which is what apple uses).

So it remains to determine which convention is used inside an archive. This could be done during the initial scanning of the archive by using the [Normalizer::isNormalized()
](https://www.php.net/manual/de/normalizer.isnormalized.php).

Although in principle an archive could contain filenames with both convention even inside the same filename this is unlikely. So the NFD workaround would  just check if any filename in the archive does not use the NFC convention and then convert to NFD before passing names back to the archive backend for extraction.

**Comment by rotdrop** [comment] 2024-05-29 08:36
Ok, after deinstalling 7z it seems that the code in #46 also works with the ZIP driver (look at the preview icons on the screenshots)

![Screenshot_20240529_103420](https://github.com/rotdrop/nextcloud-app-files-archive/assets/1494769/ba5b3385-447b-4272-b1d3-fce058343a45)
![Screenshot_20240529_103344](https://github.com/rotdrop/nextcloud-app-files-archive/assets/1494769/b8a3bfba-ed9f-4261-bdcc-a7b4c208cc22)

**Comment by rotdrop** [comment] 2024-05-29 08:53
So my impression is that this is now fixed by 9699b44, the commit is included in the latest pre-release, can you please check whether or not this solves your problem, which IMHO was caused by different conventions about unicode normalization on different systems?

**Closed** 2024-05-29 10:56 UTC
Labels: pome
